// <auto-generated>
// Builder-prop (hard-hat + mallet) head/hand anchors, MEASURED FROM SPRITE PIXELS.
// Baked by Tools/bake_builder_anchors.py — DO NOT EDIT BY HAND. RE-RUN THAT SCRIPT
// AFTER ANY DINO ART REGEN: a re-slice moves each facing's union box and silently
// invalidates every number below. That is DinoDigger-rip, where a limb-freeze re-bake
// left the hard hats hovering off the crews' heads and the mallets beside their hands.
// `bake_builder_anchors.py --check` is the guard; BuilderAnchorsMatchArt is its runtime
// twin (it re-measures live sprites and fails on drift).
//
// Per (species, stage, facing): the head's horizontal center + width taken from the top
// 11% of the opaque bounding box, and the facing-side body extreme on the scanline 45%
// down that box, all as fractions of that facing's idle+walkA+walkB union canvas.
//
// PER GROWTH STAGE, because baby/kid are separate img2img generations rather than scaled
// adults — their measurements differ from the adult's by up to 0.37 of the sprite width
// (half a world unit of prop displacement), which is most of a hard hat.
//
// The table is keyed by LOGICAL facing (Dir8) and its values are already in
// CURRENT-FRAME renderer-bounds (canvas) coordinates, with the bw4 mirror
// correction (GeneratedArtImporter.FlippedFacingPairs) FOLDED IN: for a facing
// whose displayed sprite is the mirror-partner FILE, HeadCx/HeadW come from that
// displayed file and FrontX is placed on the visual facing side. That remap applies to
// the ADULT rows only — GeneratedArtImporter.StagePath does not consult it, so the
// baby/kid rows are measured straight off their own files. Sprites are FullRect meshes
// so renderer.bounds == the full canvas, and consumers apply the fractions directly to
// renderer.bounds with NO further mirroring. There is no runtime flipX.
// </auto-generated>
using DinoDigger.Core;

namespace DinoDigger.Config
{
    /// <summary>One head/hand anchor for a (species, stage, facing): all fractions of the
    /// current SpriteRenderer.bounds. HeadCx = head horizontal center (0=left edge);
    /// HeadW = head width; FrontX = facing-side body extreme at 45% height (mallet).</summary>
    public readonly struct BuilderPropAnchor
    {
        public readonly float HeadCx;
        public readonly float HeadW;
        public readonly float FrontX;

        /// <summary>Fraction of the opaque bbox height the head span was measured over —
        /// 0.11 normally, deeper where the baker had to look past a horn or a crest.
        /// The RUNTIME PLACEMENT NEVER READS THIS. It is shipped so the BuilderAnchorsMatchArt
        /// guard can re-measure the same band instead of re-deriving it: the span is a step
        /// function of this depth, so re-deciding it against the downsampled runtime texture
        /// can tip to the other side of the step and invent drift that isn't there.</summary>
        public readonly float HeadBand;

        public BuilderPropAnchor(float headCx, float headW, float frontX, float headBand)
        {
            HeadCx = headCx; HeadW = headW; FrontX = frontX; HeadBand = headBand;
        }
    }

    /// <summary>Generated lookup of builder-gear anchors + the tuned placement
    /// multipliers, keyed [DinoType][GrowthStage][Dir8].</summary>
    public static class BuilderPropAnchors
    {
        /// <summary>Hat world width = HatWidthMul * HeadW * bounds.width.</summary>
        public const float HatWidthMul = 1.00f;
        /// <summary>Hat brim dips this fraction of the hat height below the crown.</summary>
        public const float HatCrownOverlap = 0.30f;
        /// <summary>Mallet world height = MalletHeightMul * bounds.height.</summary>
        public const float MalletHeightMul = 0.30f;
        /// <summary>Mallet grip rides this fraction DOWN from the top of the bounds.</summary>
        public const float MalletHeightFrac = 0.45f;

        /// <summary>Anchors for the sprite a dino of this species/stage/facing is
        /// ACTUALLY showing. Every index is clamped, so a future enum value degrades to
        /// the first row rather than throwing under a builder's LateUpdate.</summary>
        public static BuilderPropAnchor Get(DinoType type, GrowthStage stage, Dir8 dir)
        {
            int t = (int)type;
            int s = (int)stage;
            int d = (int)dir;
            if (t < 0 || t >= Table.Length) t = 0;
            var species = Table[t];
            if (s < 0 || s >= species.Length) s = species.Length - 1;
            var row = species[s];
            if (d < 0 || d >= row.Length) d = 0;
            return row[d];
        }

        // [DinoType][GrowthStage][Dir8] = Baby,Kid,Big x N,NE,E,SE,S,SW,W,NW
        private static readonly BuilderPropAnchor[][][] Table =
        {
            // ---- TRex
            new[]
            {
                // TRex / Baby
                new[] { new BuilderPropAnchor(0.495f, 0.747f, 0.286f, 0.110f), new BuilderPropAnchor(0.503f, 0.712f, 0.960f, 0.110f), new BuilderPropAnchor(0.481f, 0.631f, 0.943f, 0.110f), new BuilderPropAnchor(0.487f, 0.763f, 0.966f, 0.110f), new BuilderPropAnchor(0.499f, 0.741f, 0.714f, 0.110f), new BuilderPropAnchor(0.513f, 0.763f, 0.034f, 0.110f), new BuilderPropAnchor(0.519f, 0.631f, 0.057f, 0.110f), new BuilderPropAnchor(0.497f, 0.712f, 0.040f, 0.110f) },
                // TRex / Kid
                new[] { new BuilderPropAnchor(0.495f, 0.766f, 0.287f, 0.110f), new BuilderPropAnchor(0.529f, 0.674f, 0.933f, 0.110f), new BuilderPropAnchor(0.583f, 0.562f, 0.906f, 0.110f), new BuilderPropAnchor(0.559f, 0.662f, 0.894f, 0.110f), new BuilderPropAnchor(0.436f, 0.669f, 0.714f, 0.110f), new BuilderPropAnchor(0.441f, 0.662f, 0.106f, 0.110f), new BuilderPropAnchor(0.417f, 0.562f, 0.094f, 0.110f), new BuilderPropAnchor(0.471f, 0.674f, 0.067f, 0.110f) },
                // TRex / Big
                new[] { new BuilderPropAnchor(0.497f, 0.751f, 0.287f, 0.110f), new BuilderPropAnchor(0.545f, 0.683f, 0.896f, 0.110f), new BuilderPropAnchor(0.549f, 0.558f, 0.906f, 0.110f), new BuilderPropAnchor(0.437f, 0.661f, 0.766f, 0.110f), new BuilderPropAnchor(0.468f, 0.688f, 0.713f, 0.110f), new BuilderPropAnchor(0.563f, 0.661f, 0.234f, 0.110f), new BuilderPropAnchor(0.451f, 0.558f, 0.094f, 0.110f), new BuilderPropAnchor(0.455f, 0.683f, 0.104f, 0.110f) },
            },
            // ---- Triceratops
            new[]
            {
                // Triceratops / Baby
                new[] { new BuilderPropAnchor(0.498f, 0.679f, 0.285f, 0.110f), new BuilderPropAnchor(0.460f, 0.556f, 0.976f, 0.110f), new BuilderPropAnchor(0.522f, 0.460f, 0.970f, 0.136f), new BuilderPropAnchor(0.487f, 0.670f, 0.940f, 0.110f), new BuilderPropAnchor(0.499f, 0.682f, 0.715f, 0.110f), new BuilderPropAnchor(0.513f, 0.670f, 0.060f, 0.110f), new BuilderPropAnchor(0.478f, 0.460f, 0.030f, 0.136f), new BuilderPropAnchor(0.540f, 0.556f, 0.024f, 0.110f) },
                // Triceratops / Kid
                new[] { new BuilderPropAnchor(0.497f, 0.673f, 0.286f, 0.110f), new BuilderPropAnchor(0.529f, 0.717f, 0.987f, 0.110f), new BuilderPropAnchor(0.524f, 0.534f, 0.980f, 0.110f), new BuilderPropAnchor(0.468f, 0.757f, 0.895f, 0.110f), new BuilderPropAnchor(0.501f, 0.669f, 0.714f, 0.110f), new BuilderPropAnchor(0.532f, 0.757f, 0.105f, 0.110f), new BuilderPropAnchor(0.476f, 0.534f, 0.020f, 0.110f), new BuilderPropAnchor(0.471f, 0.717f, 0.013f, 0.110f) },
                // Triceratops / Big
                new[] { new BuilderPropAnchor(0.500f, 0.670f, 0.286f, 0.110f), new BuilderPropAnchor(0.534f, 0.685f, 0.977f, 0.114f), new BuilderPropAnchor(0.539f, 0.509f, 0.974f, 0.110f), new BuilderPropAnchor(0.515f, 0.755f, 0.912f, 0.110f), new BuilderPropAnchor(0.518f, 0.647f, 0.714f, 0.110f), new BuilderPropAnchor(0.485f, 0.755f, 0.088f, 0.110f), new BuilderPropAnchor(0.461f, 0.509f, 0.026f, 0.110f), new BuilderPropAnchor(0.466f, 0.685f, 0.023f, 0.114f) },
            },
            // ---- Brachiosaurus
            new[]
            {
                // Brachiosaurus / Baby
                new[] { new BuilderPropAnchor(0.505f, 0.680f, 0.286f, 0.110f), new BuilderPropAnchor(0.488f, 0.676f, 0.968f, 0.110f), new BuilderPropAnchor(0.450f, 0.681f, 0.982f, 0.110f), new BuilderPropAnchor(0.476f, 0.703f, 0.974f, 0.110f), new BuilderPropAnchor(0.487f, 0.702f, 0.714f, 0.110f), new BuilderPropAnchor(0.524f, 0.703f, 0.026f, 0.110f), new BuilderPropAnchor(0.550f, 0.681f, 0.018f, 0.110f), new BuilderPropAnchor(0.512f, 0.676f, 0.032f, 0.110f) },
                // Brachiosaurus / Kid
                new[] { new BuilderPropAnchor(0.512f, 0.708f, 0.288f, 0.110f), new BuilderPropAnchor(0.626f, 0.530f, 0.798f, 0.110f), new BuilderPropAnchor(0.648f, 0.471f, 0.712f, 0.110f), new BuilderPropAnchor(0.590f, 0.538f, 0.766f, 0.110f), new BuilderPropAnchor(0.589f, 0.496f, 0.714f, 0.110f), new BuilderPropAnchor(0.410f, 0.538f, 0.234f, 0.110f), new BuilderPropAnchor(0.352f, 0.471f, 0.288f, 0.110f), new BuilderPropAnchor(0.374f, 0.530f, 0.202f, 0.110f) },
                // Brachiosaurus / Big
                new[] { new BuilderPropAnchor(0.501f, 0.675f, 0.288f, 0.110f), new BuilderPropAnchor(0.461f, 0.607f, 0.749f, 0.110f), new BuilderPropAnchor(0.669f, 0.498f, 0.779f, 0.110f), new BuilderPropAnchor(0.599f, 0.533f, 0.767f, 0.110f), new BuilderPropAnchor(0.631f, 0.559f, 0.714f, 0.110f), new BuilderPropAnchor(0.401f, 0.533f, 0.233f, 0.110f), new BuilderPropAnchor(0.331f, 0.498f, 0.221f, 0.110f), new BuilderPropAnchor(0.539f, 0.607f, 0.251f, 0.110f) },
            },
            // ---- Stegosaurus
            new[]
            {
                // Stegosaurus / Baby
                new[] { new BuilderPropAnchor(0.493f, 0.442f, 0.287f, 0.110f), new BuilderPropAnchor(0.343f, 0.349f, 0.697f, 0.110f), new BuilderPropAnchor(0.635f, 0.326f, 0.964f, 0.110f), new BuilderPropAnchor(0.431f, 0.400f, 0.769f, 0.116f), new BuilderPropAnchor(0.421f, 0.408f, 0.715f, 0.114f), new BuilderPropAnchor(0.569f, 0.400f, 0.231f, 0.116f), new BuilderPropAnchor(0.365f, 0.326f, 0.036f, 0.110f), new BuilderPropAnchor(0.657f, 0.349f, 0.303f, 0.110f) },
                // Stegosaurus / Kid
                new[] { new BuilderPropAnchor(0.489f, 0.417f, 0.286f, 0.110f), new BuilderPropAnchor(0.354f, 0.378f, 0.699f, 0.116f), new BuilderPropAnchor(0.431f, 0.409f, 0.782f, 0.116f), new BuilderPropAnchor(0.440f, 0.414f, 0.781f, 0.120f), new BuilderPropAnchor(0.430f, 0.411f, 0.715f, 0.116f), new BuilderPropAnchor(0.560f, 0.414f, 0.219f, 0.120f), new BuilderPropAnchor(0.569f, 0.409f, 0.218f, 0.116f), new BuilderPropAnchor(0.646f, 0.378f, 0.301f, 0.116f) },
                // Stegosaurus / Big
                new[] { new BuilderPropAnchor(0.485f, 0.448f, 0.287f, 0.110f), new BuilderPropAnchor(0.625f, 0.379f, 0.949f, 0.110f), new BuilderPropAnchor(0.433f, 0.410f, 0.782f, 0.116f), new BuilderPropAnchor(0.576f, 0.388f, 0.933f, 0.112f), new BuilderPropAnchor(0.435f, 0.417f, 0.715f, 0.116f), new BuilderPropAnchor(0.424f, 0.388f, 0.067f, 0.112f), new BuilderPropAnchor(0.567f, 0.410f, 0.218f, 0.116f), new BuilderPropAnchor(0.375f, 0.379f, 0.051f, 0.110f) },
            },
            // ---- Pteranodon
            new[]
            {
                // Pteranodon / Baby
                new[] { new BuilderPropAnchor(0.461f, 0.438f, 0.286f, 0.110f), new BuilderPropAnchor(0.400f, 0.402f, 0.910f, 0.110f), new BuilderPropAnchor(0.453f, 0.455f, 0.974f, 0.110f), new BuilderPropAnchor(0.588f, 0.365f, 0.810f, 0.110f), new BuilderPropAnchor(0.541f, 0.399f, 0.714f, 0.110f), new BuilderPropAnchor(0.412f, 0.365f, 0.190f, 0.110f), new BuilderPropAnchor(0.547f, 0.455f, 0.026f, 0.110f), new BuilderPropAnchor(0.600f, 0.402f, 0.090f, 0.110f) },
                // Pteranodon / Kid
                new[] { new BuilderPropAnchor(0.553f, 0.313f, 0.286f, 0.170f), new BuilderPropAnchor(0.413f, 0.404f, 0.913f, 0.110f), new BuilderPropAnchor(0.425f, 0.518f, 0.972f, 0.110f), new BuilderPropAnchor(0.577f, 0.477f, 0.853f, 0.110f), new BuilderPropAnchor(0.581f, 0.416f, 0.714f, 0.110f), new BuilderPropAnchor(0.423f, 0.477f, 0.147f, 0.110f), new BuilderPropAnchor(0.575f, 0.518f, 0.028f, 0.110f), new BuilderPropAnchor(0.587f, 0.404f, 0.087f, 0.110f) },
                // Pteranodon / Big
                new[] { new BuilderPropAnchor(0.501f, 0.681f, 0.286f, 0.110f), new BuilderPropAnchor(0.372f, 0.462f, 0.936f, 0.110f), new BuilderPropAnchor(0.442f, 0.494f, 0.976f, 0.110f), new BuilderPropAnchor(0.543f, 0.358f, 0.766f, 0.110f), new BuilderPropAnchor(0.565f, 0.398f, 0.714f, 0.110f), new BuilderPropAnchor(0.457f, 0.358f, 0.234f, 0.110f), new BuilderPropAnchor(0.558f, 0.494f, 0.024f, 0.110f), new BuilderPropAnchor(0.628f, 0.462f, 0.064f, 0.110f) },
            },
            // ---- Ankylosaurus
            new[]
            {
                // Ankylosaurus / Baby
                new[] { new BuilderPropAnchor(0.507f, 0.477f, 0.287f, 0.110f), new BuilderPropAnchor(0.638f, 0.415f, 0.985f, 0.110f), new BuilderPropAnchor(0.656f, 0.384f, 0.982f, 0.110f), new BuilderPropAnchor(0.375f, 0.429f, 0.795f, 0.110f), new BuilderPropAnchor(0.379f, 0.423f, 0.715f, 0.110f), new BuilderPropAnchor(0.625f, 0.429f, 0.205f, 0.110f), new BuilderPropAnchor(0.344f, 0.384f, 0.018f, 0.110f), new BuilderPropAnchor(0.362f, 0.415f, 0.015f, 0.110f) },
                // Ankylosaurus / Kid
                new[] { new BuilderPropAnchor(0.505f, 0.583f, 0.287f, 0.110f), new BuilderPropAnchor(0.384f, 0.403f, 0.942f, 0.110f), new BuilderPropAnchor(0.337f, 0.368f, 0.795f, 0.110f), new BuilderPropAnchor(0.369f, 0.419f, 0.929f, 0.110f), new BuilderPropAnchor(0.368f, 0.411f, 0.715f, 0.110f), new BuilderPropAnchor(0.631f, 0.419f, 0.071f, 0.110f), new BuilderPropAnchor(0.663f, 0.368f, 0.205f, 0.110f), new BuilderPropAnchor(0.616f, 0.403f, 0.058f, 0.110f) },
                // Ankylosaurus / Big
                new[] { new BuilderPropAnchor(0.529f, 0.657f, 0.287f, 0.110f), new BuilderPropAnchor(0.603f, 0.387f, 0.912f, 0.110f), new BuilderPropAnchor(0.652f, 0.358f, 0.981f, 0.110f), new BuilderPropAnchor(0.645f, 0.395f, 0.988f, 0.110f), new BuilderPropAnchor(0.398f, 0.403f, 0.715f, 0.110f), new BuilderPropAnchor(0.355f, 0.395f, 0.012f, 0.110f), new BuilderPropAnchor(0.348f, 0.358f, 0.019f, 0.110f), new BuilderPropAnchor(0.397f, 0.387f, 0.088f, 0.110f) },
            },
            // ---- Spinosaurus
            new[]
            {
                // Spinosaurus / Baby
                new[] { new BuilderPropAnchor(0.508f, 0.651f, 0.284f, 0.110f), new BuilderPropAnchor(0.475f, 0.483f, 0.984f, 0.110f), new BuilderPropAnchor(0.558f, 0.581f, 0.983f, 0.110f), new BuilderPropAnchor(0.560f, 0.613f, 0.980f, 0.110f), new BuilderPropAnchor(0.570f, 0.606f, 0.716f, 0.110f), new BuilderPropAnchor(0.440f, 0.613f, 0.020f, 0.110f), new BuilderPropAnchor(0.442f, 0.581f, 0.017f, 0.110f), new BuilderPropAnchor(0.525f, 0.483f, 0.016f, 0.110f) },
                // Spinosaurus / Kid
                new[] { new BuilderPropAnchor(0.501f, 0.637f, 0.284f, 0.110f), new BuilderPropAnchor(0.499f, 0.460f, 0.983f, 0.110f), new BuilderPropAnchor(0.567f, 0.617f, 0.971f, 0.110f), new BuilderPropAnchor(0.560f, 0.622f, 0.976f, 0.110f), new BuilderPropAnchor(0.559f, 0.612f, 0.716f, 0.110f), new BuilderPropAnchor(0.440f, 0.622f, 0.024f, 0.110f), new BuilderPropAnchor(0.433f, 0.617f, 0.029f, 0.110f), new BuilderPropAnchor(0.501f, 0.460f, 0.017f, 0.110f) },
                // Spinosaurus / Big
                new[] { new BuilderPropAnchor(0.431f, 0.631f, 0.284f, 0.110f), new BuilderPropAnchor(0.451f, 0.449f, 0.985f, 0.110f), new BuilderPropAnchor(0.563f, 0.613f, 0.978f, 0.110f), new BuilderPropAnchor(0.570f, 0.624f, 0.964f, 0.110f), new BuilderPropAnchor(0.567f, 0.627f, 0.716f, 0.110f), new BuilderPropAnchor(0.430f, 0.624f, 0.036f, 0.110f), new BuilderPropAnchor(0.437f, 0.613f, 0.022f, 0.110f), new BuilderPropAnchor(0.549f, 0.449f, 0.015f, 0.110f) },
            },
            // ---- Parasaurolophus
            new[]
            {
                // Parasaurolophus / Baby
                new[] { new BuilderPropAnchor(0.486f, 0.326f, 0.287f, 0.180f), new BuilderPropAnchor(0.454f, 0.461f, 0.935f, 0.110f), new BuilderPropAnchor(0.528f, 0.305f, 0.986f, 0.180f), new BuilderPropAnchor(0.468f, 0.301f, 0.974f, 0.130f), new BuilderPropAnchor(0.500f, 0.302f, 0.713f, 0.180f), new BuilderPropAnchor(0.532f, 0.301f, 0.026f, 0.130f), new BuilderPropAnchor(0.472f, 0.305f, 0.014f, 0.180f), new BuilderPropAnchor(0.546f, 0.461f, 0.065f, 0.110f) },
                // Parasaurolophus / Kid
                new[] { new BuilderPropAnchor(0.498f, 0.350f, 0.287f, 0.180f), new BuilderPropAnchor(0.486f, 0.302f, 0.933f, 0.180f), new BuilderPropAnchor(0.472f, 0.307f, 0.974f, 0.110f), new BuilderPropAnchor(0.535f, 0.309f, 0.974f, 0.160f), new BuilderPropAnchor(0.510f, 0.336f, 0.713f, 0.190f), new BuilderPropAnchor(0.465f, 0.309f, 0.026f, 0.160f), new BuilderPropAnchor(0.528f, 0.307f, 0.026f, 0.110f), new BuilderPropAnchor(0.514f, 0.302f, 0.067f, 0.180f) },
                // Parasaurolophus / Big
                new[] { new BuilderPropAnchor(0.464f, 0.305f, 0.287f, 0.110f), new BuilderPropAnchor(0.364f, 0.351f, 0.981f, 0.110f), new BuilderPropAnchor(0.479f, 0.308f, 0.983f, 0.110f), new BuilderPropAnchor(0.550f, 0.306f, 0.971f, 0.180f), new BuilderPropAnchor(0.564f, 0.309f, 0.713f, 0.200f), new BuilderPropAnchor(0.450f, 0.306f, 0.029f, 0.180f), new BuilderPropAnchor(0.521f, 0.308f, 0.017f, 0.110f), new BuilderPropAnchor(0.636f, 0.351f, 0.019f, 0.110f) },
            },
            // ---- Velociraptor
            new[]
            {
                // Velociraptor / Baby
                new[] { new BuilderPropAnchor(0.493f, 0.784f, 0.287f, 0.110f), new BuilderPropAnchor(0.507f, 0.683f, 0.935f, 0.110f), new BuilderPropAnchor(0.517f, 0.613f, 0.935f, 0.110f), new BuilderPropAnchor(0.538f, 0.725f, 0.971f, 0.110f), new BuilderPropAnchor(0.476f, 0.729f, 0.714f, 0.110f), new BuilderPropAnchor(0.462f, 0.725f, 0.029f, 0.110f), new BuilderPropAnchor(0.483f, 0.613f, 0.065f, 0.110f), new BuilderPropAnchor(0.493f, 0.683f, 0.065f, 0.110f) },
                // Velociraptor / Kid
                new[] { new BuilderPropAnchor(0.500f, 0.755f, 0.287f, 0.110f), new BuilderPropAnchor(0.508f, 0.730f, 0.946f, 0.110f), new BuilderPropAnchor(0.530f, 0.590f, 0.887f, 0.110f), new BuilderPropAnchor(0.527f, 0.734f, 0.907f, 0.110f), new BuilderPropAnchor(0.545f, 0.692f, 0.714f, 0.110f), new BuilderPropAnchor(0.473f, 0.734f, 0.093f, 0.110f), new BuilderPropAnchor(0.470f, 0.590f, 0.113f, 0.110f), new BuilderPropAnchor(0.492f, 0.730f, 0.054f, 0.110f) },
                // Velociraptor / Big
                new[] { new BuilderPropAnchor(0.414f, 0.631f, 0.286f, 0.110f), new BuilderPropAnchor(0.606f, 0.599f, 0.948f, 0.110f), new BuilderPropAnchor(0.552f, 0.570f, 0.904f, 0.110f), new BuilderPropAnchor(0.399f, 0.625f, 0.679f, 0.110f), new BuilderPropAnchor(0.393f, 0.649f, 0.715f, 0.110f), new BuilderPropAnchor(0.601f, 0.625f, 0.321f, 0.110f), new BuilderPropAnchor(0.448f, 0.570f, 0.096f, 0.110f), new BuilderPropAnchor(0.394f, 0.599f, 0.052f, 0.110f) },
            },
        };
    }
}
