// <auto-generated>
// Builder-prop (hard-hat + mallet) head/hand anchors, MEASURED FROM SPRITE PIXELS.
// Source measurement: head_anchors.json (per-species x per-facing head center,
// head width, and facing-side body extreme at 45% height, as fractions of the
// opaque-pixel bounding box of each facing's idle+walkA+walkB union).
// Baked by Tools-scratchpad bake_anchors.py. DO NOT EDIT BY HAND.
//
// The table is keyed by LOGICAL facing (Dir8) and its values are already in
// CURRENT-FRAME renderer-bounds (canvas) coordinates, with the bw4 mirror
// correction (GeneratedArtImporter.FlippedFacingPairs) FOLDED IN: for a facing
// whose displayed sprite is the mirror-partner FILE, HeadCx/HeadW come from that
// displayed file and FrontX is placed on the visual facing side. Sprites are
// FullRect meshes so renderer.bounds == the full canvas; the small opaque->canvas
// margin is compensated here, so consumers apply the fractions directly to
// renderer.bounds with NO further mirroring. There is no runtime flipX.
// </auto-generated>
using DinoDigger.Core;

namespace DinoDigger.Config
{
    /// <summary>One head/hand anchor for a (species, facing): all fractions of the
    /// current SpriteRenderer.bounds. HeadCx = head horizontal center (0=left edge);
    /// HeadW = head width; FrontX = facing-side body extreme at 45% height (mallet).</summary>
    public readonly struct BuilderPropAnchor
    {
        public readonly float HeadCx;
        public readonly float HeadW;
        public readonly float FrontX;
        public BuilderPropAnchor(float headCx, float headW, float frontX)
        {
            HeadCx = headCx; HeadW = headW; FrontX = frontX;
        }
    }

    /// <summary>Generated lookup of builder-gear anchors + the tuned placement
    /// multipliers, keyed [DinoType][Dir8].</summary>
    public static class BuilderPropAnchors
    {
        /// <summary>Hat world width = HatWidthMul * HeadW * bounds.width.</summary>
        public const float HatWidthMul = 1.00f;
        /// <summary>Hat brim dips this fraction of the hat height below the crown.</summary>
        public const float HatCrownOverlap = 0.30f;
        /// <summary>Mallet world height = MalletHeightMul * bounds.height.</summary>
        public const float MalletHeightMul = 0.30f;
        /// <summary>Mallet grip rides this fraction DOWN from the top of the bounds.</summary>
        public const float MalletHeightFrac = 0.45f;

        public static BuilderPropAnchor Get(DinoType type, Dir8 dir)
        {
            int t = (int)type;
            int d = (int)dir;
            if (t < 0 || t >= Table.Length) t = 0;
            var row = Table[t];
            if (d < 0 || d >= row.Length) d = 0;
            return row[d];
        }

        // [DinoType][Dir8] = N,NE,E,SE,S,SW,W,NW
        private static readonly BuilderPropAnchor[][] Table =
        {
            // TRex
            new[] { new BuilderPropAnchor(0.495f, 0.751f, 0.287f), new BuilderPropAnchor(0.545f, 0.681f, 0.896f), new BuilderPropAnchor(0.548f, 0.552f, 0.904f), new BuilderPropAnchor(0.439f, 0.657f, 0.765f), new BuilderPropAnchor(0.469f, 0.688f, 0.713f), new BuilderPropAnchor(0.560f, 0.657f, 0.233f), new BuilderPropAnchor(0.450f, 0.552f, 0.094f), new BuilderPropAnchor(0.454f, 0.681f, 0.102f) },
            // Triceratops
            new[] { new BuilderPropAnchor(0.499f, 0.670f, 0.286f), new BuilderPropAnchor(0.505f, 0.658f, 0.982f), new BuilderPropAnchor(0.521f, 0.488f, 0.970f), new BuilderPropAnchor(0.480f, 0.577f, 0.882f), new BuilderPropAnchor(0.499f, 0.671f, 0.714f), new BuilderPropAnchor(0.518f, 0.577f, 0.119f), new BuilderPropAnchor(0.478f, 0.488f, 0.029f), new BuilderPropAnchor(0.493f, 0.658f, 0.016f) },
            // Brachiosaurus
            new[] { new BuilderPropAnchor(0.500f, 0.670f, 0.288f), new BuilderPropAnchor(0.551f, 0.710f, 0.797f), new BuilderPropAnchor(0.647f, 0.528f, 0.773f), new BuilderPropAnchor(0.613f, 0.575f, 0.799f), new BuilderPropAnchor(0.593f, 0.597f, 0.713f), new BuilderPropAnchor(0.385f, 0.575f, 0.199f), new BuilderPropAnchor(0.351f, 0.528f, 0.225f), new BuilderPropAnchor(0.448f, 0.710f, 0.202f) },
            // Stegosaurus
            new[] { new BuilderPropAnchor(0.485f, 0.444f, 0.287f), new BuilderPropAnchor(0.602f, 0.353f, 0.963f), new BuilderPropAnchor(0.413f, 0.384f, 0.776f), new BuilderPropAnchor(0.576f, 0.393f, 0.801f), new BuilderPropAnchor(0.401f, 0.299f, 0.715f), new BuilderPropAnchor(0.423f, 0.393f, 0.201f), new BuilderPropAnchor(0.586f, 0.384f, 0.223f), new BuilderPropAnchor(0.396f, 0.353f, 0.035f) },
            // Pteranodon
            new[] { new BuilderPropAnchor(0.500f, 0.491f, 0.286f), new BuilderPropAnchor(0.384f, 0.349f, 0.912f), new BuilderPropAnchor(0.457f, 0.413f, 0.974f), new BuilderPropAnchor(0.528f, 0.298f, 0.764f), new BuilderPropAnchor(0.548f, 0.314f, 0.714f), new BuilderPropAnchor(0.470f, 0.298f, 0.235f), new BuilderPropAnchor(0.541f, 0.413f, 0.024f), new BuilderPropAnchor(0.614f, 0.349f, 0.086f) },
            // Ankylosaurus
            new[] { new BuilderPropAnchor(0.503f, 0.574f, 0.287f), new BuilderPropAnchor(0.642f, 0.378f, 0.958f), new BuilderPropAnchor(0.605f, 0.371f, 0.963f), new BuilderPropAnchor(0.647f, 0.370f, 0.938f), new BuilderPropAnchor(0.374f, 0.419f, 0.715f), new BuilderPropAnchor(0.351f, 0.370f, 0.064f), new BuilderPropAnchor(0.393f, 0.371f, 0.038f), new BuilderPropAnchor(0.356f, 0.378f, 0.043f) },
            // Spinosaurus
            new[] { new BuilderPropAnchor(0.431f, 0.626f, 0.284f), new BuilderPropAnchor(0.452f, 0.447f, 0.984f), new BuilderPropAnchor(0.562f, 0.608f, 0.976f), new BuilderPropAnchor(0.571f, 0.620f, 0.963f), new BuilderPropAnchor(0.568f, 0.624f, 0.716f), new BuilderPropAnchor(0.428f, 0.620f, 0.035f), new BuilderPropAnchor(0.437f, 0.608f, 0.023f), new BuilderPropAnchor(0.547f, 0.447f, 0.015f) },
            // Parasaurolophus
            new[] { new BuilderPropAnchor(0.464f, 0.305f, 0.287f), new BuilderPropAnchor(0.373f, 0.349f, 0.979f), new BuilderPropAnchor(0.477f, 0.300f, 0.979f), new BuilderPropAnchor(0.523f, 0.247f, 0.969f), new BuilderPropAnchor(0.556f, 0.239f, 0.713f), new BuilderPropAnchor(0.475f, 0.247f, 0.029f), new BuilderPropAnchor(0.521f, 0.300f, 0.019f), new BuilderPropAnchor(0.625f, 0.349f, 0.019f) },
            // Velociraptor
            new[] { new BuilderPropAnchor(0.413f, 0.630f, 0.286f), new BuilderPropAnchor(0.605f, 0.599f, 0.948f), new BuilderPropAnchor(0.565f, 0.569f, 0.905f), new BuilderPropAnchor(0.398f, 0.625f, 0.677f), new BuilderPropAnchor(0.477f, 0.538f, 0.715f), new BuilderPropAnchor(0.600f, 0.625f, 0.321f), new BuilderPropAnchor(0.435f, 0.569f, 0.094f), new BuilderPropAnchor(0.393f, 0.599f, 0.052f) },
        };
    }
}
