// <auto-generated>
// WHICH (species, stage, facing) CELLS OF THE GENERATED ART ARE DRAWN MIRRORED against
// their own filename — MEASURED FROM SOURCE-PNG PIXELS by Tools/verify_facing_art.py.
// DO NOT EDIT BY HAND. RE-RUN THAT SCRIPT AFTER ANY DINO ART REGEN.
//
// This is the DinoDigger-bw4 / DinoDigger-3yb scar: several generated cells came back
// facing the opposite way from the direction their filename claims, so the importer
// resolves those cells to their MIRROR PARTNER's file
// (GeneratedArtImporter.FlippedFacingPairs). That table is hand-maintained and was wrong
// twice — per-actor when the fault is per (actor, STAGE, facing), and consulted by
// AdultSuffix but not by StagePath — which shipped adult stegosaurus and kid
// ankylosaurus backwards for months.
//
// So the decision is a measurement, and this file is the measurement's verdict. The
// FacingArtNotMirrored integration case reads the sprite the game would DISPLAY for
// every (species, stage, facing) and asserts its source file is the one this manifest
// implies — a wrong table entry, a stale table entry, and a path helper that forgets the
// table all fail there. `verify_facing_art.py --check` is the offline half: it
// re-measures the art and fails if this file, the importer's table, or the anchor
// baker's copy has drifted from it.
//
// WHY THE GUARD READS A BAKED TABLE INSTEAD OF RE-MEASURING PIXELS AT RUNTIME: it cannot
// re-measure. The eye-finder needs the ~800px source raster; the texture Unity ships is
// 256px tall (the WebGL override in every dino .meta) and crunch-compressed, and at that
// size no pupil survives the erosion and no sclera survives the resample — a runtime
// re-measurement finds zero eyes on all 54 E/W sprites. Nothing about texture Read/Write
// changes that (the pixels come back fine through a blit); the resolution does.
//
// Entries are the RIGHT-side member (E/SE/NE) of each mirrored pair; W/SW/NW are exact
// pixel mirrors made by slice_sprites.py, so flipping a pair covers both. N and S have no
// horizontal component and can never be flipped.
// </auto-generated>
using DinoDigger.Core;

namespace DinoDigger.Config
{
    /// <summary>The audited handedness of the generated actor art: for each (species,
    /// growth stage) the facings whose art is drawn mirrored against its filename, and so
    /// the facings the importer must resolve to their mirror partner's FILE.</summary>
    public static class FacingManifest
    {
        // Indexed [(int)DinoType * 3 + (int)GrowthStage] — DinoType and GrowthStage
        // declaration order (GameEnums.cs); Baby, Kid, Big.
        private static readonly Dir8[][] DinoFlips =
        {
            new Dir8[] { Dir8.SE },                // TRex / Baby
            new Dir8[] { },                        // TRex / Kid
            new Dir8[] { Dir8.SE },                // TRex / Big
            new Dir8[] { },                        // Triceratops / Baby
            new Dir8[] { Dir8.SE },                // Triceratops / Kid
            new Dir8[] { Dir8.SE },                // Triceratops / Big
            new Dir8[] { },                        // Brachiosaurus / Baby
            new Dir8[] { },                        // Brachiosaurus / Kid
            new Dir8[] { },                        // Brachiosaurus / Big
            new Dir8[] { Dir8.SE, Dir8.NE },       // Stegosaurus / Baby
            new Dir8[] { Dir8.E, Dir8.SE, Dir8.NE }, // Stegosaurus / Kid
            new Dir8[] { Dir8.E, Dir8.SE },        // Stegosaurus / Big
            new Dir8[] { },                        // Pteranodon / Baby
            new Dir8[] { },                        // Pteranodon / Kid
            new Dir8[] { },                        // Pteranodon / Big
            new Dir8[] { Dir8.SE },                // Ankylosaurus / Baby
            new Dir8[] { Dir8.E, Dir8.SE, Dir8.NE }, // Ankylosaurus / Kid
            new Dir8[] { Dir8.E, Dir8.SE, Dir8.NE }, // Ankylosaurus / Big
            new Dir8[] { },                        // Spinosaurus / Baby
            new Dir8[] { },                        // Spinosaurus / Kid
            new Dir8[] { },                        // Spinosaurus / Big
            new Dir8[] { },                        // Parasaurolophus / Baby
            new Dir8[] { },                        // Parasaurolophus / Kid
            new Dir8[] { },                        // Parasaurolophus / Big
            new Dir8[] { },                        // Velociraptor / Baby
            new Dir8[] { },                        // Velociraptor / Kid
            new Dir8[] { Dir8.SE },                // Velociraptor / Big
        };

        // The backhoe has one art set (no growth stages).
        private static readonly Dir8[] BackhoeFlips = new Dir8[] { Dir8.SE, Dir8.NE };   // backhoe / adult

        /// <summary>The facing whose FILE the game must display for a logical facing —
        /// the logical facing itself, or its mirror partner where the art is
        /// backwards.</summary>
        public static Dir8 DisplayedFacing(DinoType type, GrowthStage stage, Dir8 logical)
        {
            return Contains(Row(type, stage), logical) ? Mirror(logical) : logical;
        }

        /// <summary>DisplayedFacing for the backhoe, which has no growth stages.</summary>
        public static Dir8 DisplayedBackhoeFacing(Dir8 logical)
        {
            return Contains(BackhoeFlips, logical) ? Mirror(logical) : logical;
        }

        /// <summary>Horizontal mirror of a facing (N/S are their own mirrors).</summary>
        public static Dir8 Mirror(Dir8 d)
        {
            switch (d)
            {
                case Dir8.E: return Dir8.W;
                case Dir8.W: return Dir8.E;
                case Dir8.NE: return Dir8.NW;
                case Dir8.NW: return Dir8.NE;
                case Dir8.SE: return Dir8.SW;
                case Dir8.SW: return Dir8.SE;
                default: return d;
            }
        }

        private static Dir8[] Row(DinoType type, GrowthStage stage)
        {
            int i = (int)type * 3 + (int)stage;
            return i >= 0 && i < DinoFlips.Length ? DinoFlips[i] : System.Array.Empty<Dir8>();
        }

        /// <summary>Is this facing's mirror PAIR flagged? Both members of a pair share the
        /// one entry, stored under its right-side member.</summary>
        private static bool Contains(Dir8[] row, Dir8 d)
        {
            Dir8 key = d == Dir8.W ? Dir8.E : d == Dir8.SW ? Dir8.SE : d == Dir8.NW ? Dir8.NE : d;
            for (int i = 0; i < row.Length; i++)
            {
                if (row[i] == key)
                {
                    return true;
                }
            }

            return false;
        }
    }
}
